export const constants: constTypes = {
  ACTIVE_DEPOSIT_DURATION: 200,
  CONTRACT: 'kompwnd',
  REFERRAL_PERCENTAGE: 0.1,
  FEE_PERCENTAGE: 0.1,
  ROLL_PERCENTAGE: 0.9,
  DAILY_REWARD_PERCENTAGE: 0.005,
  CLAIM_DIV_THRESHOLD: 50,
  ROLL_DIV_THRESHOLD: 40,
  ZERO_KPW: '0.0000 KPW',
} as const;

type constTypes = {
  ACTIVE_DEPOSIT_DURATION: number;
  CONTRACT: string;
  REFERRAL_PERCENTAGE: number;
  FEE_PERCENTAGE: number;
  ROLL_PERCENTAGE: number;
  DAILY_REWARD_PERCENTAGE: number;
  CLAIM_DIV_THRESHOLD: number;
  ROLL_DIV_THRESHOLD: number;
  ZERO_KPW: string;
};
